version: "3.4"

services:
  cards.webapi:
    image: ${DOCKER_REGISTRY-}cardswebapi
    build:
      context: .
      dockerfile: Cards.WebApi/Dockerfile
    ports:
      #    - 2080:80
      - 80:80
    #   - 443:443
